# https://help.github.com/en/actions

# https://github.com/actions
# https://github.com/actions/checkout
# https://github.com/actions/setup-node

name: CI on Push

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - 'LICENSE'
      - '**.md'
      - '.gitignore'
      - '.npmignore'
      - '.vscode/**'
      - '.github/FUNDING.yml'
      - 'typedoc.json'

# os: [ubuntu-24.04, macos-13, macos-14, windows-2022]

jobs:
  linux-x64-test:

    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      # https://github.com/actions/checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Node.js
      # https://github.com/actions/setup-node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Show node & npm versions, environment
      run: |
        node --version
        npm --version
        env | sort | grep -E '^[^ \t]+='

    - name: Install xpm
      run: npm install --location=global xpm

    - name: Install xpm dependencies
      run: xpm install

    - name: Run test
      run: xpm run test-ci
      env:
        CI: true

  win32-x64-test:

    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
    runs-on: windows-2022
    defaults:
      run:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
        shell: bash # for --

    steps:
    - name: Checkout
      # https://github.com/actions/checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Node.js
      # https://github.com/actions/setup-node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Show node & npm versions, environment
      run: |
        node --version
        npm --version
        env | sort | grep -E '^[^ \t]+='

    - name: Install xpm
      run: npm install --location=global xpm

    - name: Install xpm dependencies
      run: xpm install

    - name: Run test
      run: xpm run test-ci
      env:
        CI: true

  darwin-x64-test:

    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
    runs-on:  macos-13

    steps:
    - name: Checkout
      # https://github.com/actions/checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Node.js
      # https://github.com/actions/setup-node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Show node & npm versions, environment
      run: |
        uname -a
        sw_vers
        ls -lA /Library/Developer/CommandLineTools/SDKs || true
        ls -lA /Applications
        sudo xcode-select --switch /Applications/Xcode_14.2.app
        xcode-select --print-path
        xcodebuild -version || true
        pkgutil --pkg-info=com.apple.pkg.CLTools_Executables || true
        clang++ -v
        node --version
        npm --version
        env | sort | grep -E '^[^ \t]+='

    - name: Install xpm
      run: npm install --location=global xpm

    - name: Install xpm dependencies
      run: xpm install

    - name: Run test
      run: xpm run test-ci
      env:
        CI: true

  darwin-arm64-test:

    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
    runs-on:  macos-14

    steps:
    - name: Checkout
      # https://github.com/actions/checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Node.js
      # https://github.com/actions/setup-node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Show node & npm versions, environment
      run: |
        uname -a
        sw_vers
        ls -lA /Library/Developer/CommandLineTools/SDKs || true
        ls -lA /Applications
        sudo xcode-select --switch /Applications/Xcode_15.4.app
        xcode-select --print-path
        xcodebuild -version || true
        pkgutil --pkg-info=com.apple.pkg.CLTools_Executables || true
        clang++ -v
        node --version
        npm --version
        env | sort | grep -E '^[^ \t]+='

    - name: Install xpm
      run: npm install --location=global xpm

    - name: Install xpm dependencies
      run: xpm install

    - name: Run test
      run: xpm run test-ci
      env:
        CI: true
